@base_url = http://localhost
@port = 4800
@url = {{base_url}}:{{port}}
@equipment_api = {{url}}/equipments

@account_api = {{url}}/account

@token = Bearer {{login.response.body.token}}


// get all
GET {{equipment_api}} HTTP/1.1
Authorization: {{token}}
###

// get by ID
GET {{equipment_api}}/1 HTTP/1.1
Authorization: {{token}}

###


// add equipment
POST {{equipment_api}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "item_name": "Galaxy S22",
    "category": "smartphone",
    "brand": "Samsung",
    "model": "ABC123",
    "serial_number" : "CA01" ,
    "image": "-",
    "project_name": "XXX 101",
    "status": "stock",
    "borrower": "-",
    "pv_number" : "-",
    "po_number": "-",
    "locate_at": "ACE"
}
###

DELETE {{equipment_api}}/2 HTTP/1.1
Authorization: {{token}}

###


// get by serial number
GET {{equipment_api}}/sn/SS112231 HTTP/1.1
Authorization: {{token}}

###


// edit
PUT {{equipment_api}}/1 HTTP/1.1
Content-Type: application/json

{
    "item_name": "Galaxy Note33",
    "category": "smartphone",
    "brand": "Samsung",
    "model": "ABC123",
    "serial_number" : "CA01" ,
    "image": "-",
    "project_name": "BB 301",
    "status": "stock",
    "borrower": "Mr. Thossaporn Sukprasomjit",
    "pv_number" : "-",
    "po_number": "-",
    "locate_at": "ACE"
}
###

// register
POST {{account_api}}/register HTTP/1.1
Content-Type: application/json

{
    "username" : "admin6",
    "password" : "1234",
}
###

# @name login
//login
POST {{account_api}}/login HTTP/1.1
Content-Type: application/json

{
    "username" : "admin4",
    "password" : "1234"
}
###
